--EX05 MASKED NAMES

SELECT
       CONCAT(SUBSTR(FIRST_NAME, 1, 2), RPAD('*', LENGTH(FIRST_NAME) - 2, '*')) || ' ' ||
       CONCAT(SUBSTR(LAST_NAME, 1, 2), RPAD('*', LENGTH(LAST_NAME) - 2, '*')) AS MASKED_NAMES
FROM EMPLOYEES;

