--ex01
SELECT
    DEPARTMENT_ID,
    LISTAGG(FIRST_NAME || ' ' || LAST_NAME, '; ') WITHIN GROUP (ORDER BY FIRST_NAME, LAST_NAME) AS EMPLOYEE_NAMES
FROM
    EMPLOYEES
GROUP BY
    DEPARTMENT_ID
ORDER BY
    DEPARTMENT_ID;



--ex02
SELECT
    EMPLOYEE_ID,
    JOB_ID,
    SALARY,
    HIRE_DATE,
    NVL(
        SUM(SALARY) OVER (PARTITION BY JOB_ID ORDER BY HIRE_DATE ROWS BETWEEN 1 PRECEDING AND 1 PRECEDING),
        0
    ) AS PRECEDING,
    NVL(
        SUM(SALARY) OVER (PARTITION BY JOB_ID ORDER BY HIRE_DATE ROWS BETWEEN 1 FOLLOWING AND 1 FOLLOWING),
        0
    ) AS FOLLOWING
FROM
    EMPLOYEES
ORDER BY
    JOB_ID,
    HIRE_DATE;
    
--EX03

SELECT
    EMPLOYEE_ID,
    DEPARTMENT_ID,
    SALARY
FROM
    EMPLOYEES
WHERE
    SALARY < (SELECT MAX(SALARY) 
              FROM EMPLOYEES e2
              WHERE e2.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID)
ORDER BY
    DEPARTMENT_ID,
    SALARY;

--ex04
SELECT
    EMPLOYEE_ID,
    HIRE_DATE,
    EXTRACT(YEAR FROM HIRE_DATE) AS HIRE_YEAR
FROM
    EMPLOYEES
ORDER BY
    EXTRACT(YEAR FROM HIRE_DATE),
    HIRE_DATE;
    
--ex05
SELECT
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    LAG(SALARY) OVER (ORDER BY HIRE_DATE) AS SALARY_BEFORE,
    LEAD(SALARY) OVER (ORDER BY HIRE_DATE) AS SALARY_AFTER
FROM
    EMPLOYEES
ORDER BY
    HIRE_DATE;







