#!/usr/bin/bash 

read -p 'Please input an operand: ' operand


fact(){
	local n=$1
    	local result=1

	if [ $n -eq 0 ]; then
        	result=1
    	else
        	for (( i = 1; i <= n; i++ )); do
                result=$(( result * i ))
        done
    	fi

    	echo $result
 }





if [ $operand == "+" ]; then
	read -p 'Input 1st number: ' num1
	read -p 'Input 2nd number: ' num2
	echo "Result is $( expr $num1 + $num2 )"

elif [ $operand == "-" ]; then
	read -p 'Input 1st number: ' num1
	read -p 'Input 2nd number: ' num2
	echo "Result is $( expr $num1 - $num2 )"

elif [ $operand == "*" ]; then 
	read -p 'Input 1st number: ' num1
	read -p 'Input 2nd number: ' num2
	echo "Result is $(( $num1 * $num2 ))"


elif [ $operand == "/" ]; then 
	read -p 'Input 1st number: ' num1
	read -p 'Input 2nd number: ' num2
	echo "Result is $( expr $num1 / $num2 )"


elif [ $operand == "%" ]; then 
	read -p 'Input 1st number: ' num1
	read -p 'Input 2nd number: ' num2
	echo "Result is $( expr $num1 % $num2 )"


elif [ $operand == "!" ]; then 
	read -p 'Input the number: ' num
	echo "Result is $( fact $num )"

else 
	echo "Invalid operand error! Try again." 

fi
	

#UFAK BİR NOT: çarpma işlemi için sürekli hata alıyorum. Çözümünü bulamadım..