--EX05: MY_EMP_TABLE

--CREATE TABLE
CREATE TABLE MY_EMP_TABLE
(
    EMP_ID VARCHAR2(10),
    LAST_NAME VARCHAR2(50),
    FIRST_NAME VARCHAR2(50),
    SALARY NUMBER
);

--INSERT MULTIPLE VALUES
INSERT ALL
    INTO MY_EMP_TABLE (EMP_ID, LAST_NAME, FIRST_NAME, SALARY) VALUES ('1', 'BLACK', 'JOHN',1100)
    INTO MY_EMP_TABLE (EMP_ID, LAST_NAME, FIRST_NAME, SALARY) VALUES ('2', 'WHITE', 'KENT',1300)
    INTO MY_EMP_TABLE (EMP_ID, LAST_NAME, FIRST_NAME, SALARY) VALUES ('3', 'ORANGE', 'DAVID',1700)
    INTO MY_EMP_TABLE (EMP_ID, LAST_NAME, FIRST_NAME, SALARY) VALUES ('4', 'PINK', 'ALISSA',1900)
SELECT * FROM dual;

--UPDATE
UPDATE MY_EMP_TABLE
SET SALARY = SALARY*1.10;

--DELETE
DELETE FROM MY_EMP_TABLE WHERE FIRST_NAME='DAVID';

--TRUNCATE
TRUNCATE TABLE MY_EMP_TABLE;
