-- EX03 OPERATORS AND THEIR SUBSCRIBER NUMBERS 


SELECT 
    SUBSTR(PHONE_NUMBER, 1, 3) AS OPERATOR,
    COUNT(*) AS SUBSCRIBER
FROM EMPLOYEES
GROUP BY SUBSTR(PHONE_NUMBER, 1, 3)
ORDER BY OPERATOR;



