CREATE TABLE UNIQUE_DEPTS AS
SELECT DISTINCT DEPARTMENT_ID
FROM EMPLOYEES;

ALTER TABLE UNIQUE_DEPTS
ADD DEPARTMENT_NAME VARCHAR2(50);

MERGE INTO UNIQUE_DEPTS UD
USING DEPARTMENTS d
ON (UD.DEPARTMENT_ID = D.DEPARTMENT_ID)
WHEN MATCHED THEN
    UPDATE SET UD.DEPARTMENT_NAME = D.DEPARTMENT_NAME;
    
MERGE INTO UNIQUE_DEPTS UD
USING DEPARTMENTS D
ON (UD.DEPARTMENT_ID = D.DEPARTMENT_ID)
WHEN NOT MATCHED THEN
    INSERT (DEPARTMENT_ID, DEPARTMENT_NAME)
    VALUES (D.DEPARTMENT_ID, D.DEPARTMENT_NAME);


SELECT * FROM UNIQUE_DEPTS;

