--ex02

--DEFINE INDEX
CREATE INDEX DEPR_NAME_IDX ON DEPARTMENTS(DEPARTMENT_NAME);

--DEFINE CONSTRAINT
ALTER TABLE EMPLOYEES ADD CONSTRAINT CNSTR_SALARY CHECK (SALARY BETWEEN 1000 AND 100000);

--DROP INDEX
DROP INDEX DEPR_NAME_IDX;

--ENABLE
ALTER TABLE EMPLOYEES ENABLE CONSTRAINT CNSTR_SALARY;

--DISABLE
ALTER TABLE EMPLOYEES DISABLE CONSTRAINT CNSTR_SALARY;

--DROP CONSTRAINT
ALTER TABLE EMPLOYEES DROP CONSTRAINT CNSTR_SALARY;